import sys

# Indentation helper
def sp(n):
    return ' ' * n

# Build new block lines
lines = []
lines.append(f'{sp(10)}{{(() => {{')
lines.append(f'{sp(12)}// Group schedules by relatedMission, preserving order')
lines.append(f'{sp(12)}const groups: Record<string, AgentSchedule[]> = {{}};')
lines.append(f'{sp(12)}schedules.forEach(schedule => {{')
lines.append(f'{sp(14)}const groupKey = schedule.relatedMission || "Other";')
lines.append(f'{sp(14)}if (!groups[groupKey]) groups[groupKey] = [];')
lines.append(f'{sp(14)}groups[groupKey].push(schedule);')
lines.append(f'{sp(12)}}});')
lines.append(f'{sp(12)}const groupKeys = Object.keys(groups).sort();')
lines.append(f'{sp(12)}return groupKeys.flatMap((groupKey) => {{')
lines.append(f'{sp(14)}const groupSchedules = groups[groupKey];')
lines.append(f'{sp(14)}return [')
lines.append(f'{sp(16)}// Group heading')
lines.append(f'{sp(16)}<div key={{`heading-${{groupKey}}`}} className="mt-4 mb-2">')
lines.append(f'{sp(18)}<h3 className="text-sm font-semibold text-slate-300 uppercase tracking-wider">')
lines.append(f'{sp(20)}{{groupKey}}')
lines.append(f'{sp(18)}</h3>')
lines.append(f'{sp(16)}</div>,')
lines.append(f'{sp(16)}// Schedule buttons')
lines.append(f'{sp(16)}...groupSchedules.map((schedule) => {{')
lines.append(f'{sp(18)}const selected = selectedId === schedule.id;')
lines.append(f'{sp(18)}return (')
lines.append(f'{sp(20)}<button')
lines.append(f'{sp(22)}key={{schedule.id}}')
lines.append(f'{sp(22)}onClick={{() => onSelect(schedule.id)}}')
lines.append(f'{sp(22)}className={{`w-full rounded-[18px] border p-4 text-left transition ${{')
lines.append(f'{sp(24)}selected')
lines.append(f'{sp(26)}? "border-cyan-300/18 bg-cyan-400/8"')
lines.append(f'{sp(26)}: "border-white/8 bg-slate-950/28 hover:border-white/12 hover:bg-slate-950/34"')
lines.append(f'{sp(22)}}}`}}')
lines.append(f'{sp(20)}}}')
lines.append(f'{sp(20)}>')
lines.append(f'{sp(22)}<div className="space-y-4">')
lines.append(f'{sp(24)}<div className="grid gap-4 xl:grid-cols-[minmax(0,1.3fr)_140px_180px_180px_120px] xl:items-start">')
lines.append(f'{sp(26)}<div className="min-w-0">')
lines.append(f'{sp(28)}<div className="text-sm font-semibold text-white">')
lines.append(f'{sp(30)}{{schedule.name}}')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(28)}<div className="mt-1 text-xs uppercase tracking-[0.16em] text-slate-500">')
lines.append(f'{sp(30)}{{schedule.cadenceLabel}}')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(26)}</div>')
lines.append(f'{sp(26)}<div>')
lines.append(f'{sp(28)}<div className="text-[11px] uppercase tracking-[0.18em] text-slate-400">')
lines.append(f'{sp(30)}Agent')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(28)}<div className="mt-1">')
lines.append(f'{sp(30)}<Link')
lines.append(f'{sp(32)}href={{`/agents?agent=${{encodeURIComponent(schedule.agent)}}`}}')
lines.append(f'{sp(32)}onClick={{(e) => e.stopPropagation()}}')
lines.append(f'{sp(32)}className="text-sm text-cyan-200 transition hover:text-cyan-100"')
lines.append(f'{sp(30)}}>')
lines.append(f'{sp(32)}{{schedule.agent}}')
lines.append(f'{sp(30)}</Link>')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(26)}</div>')
lines.append(f'{sp(26)}<div>')
lines.append(f'{sp(28)}<div className="text-[11px] uppercase tracking-[0.18em] text-slate-400">')
lines.append(f'{sp(30)}Next Run')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(28)}<div className="mt-1 text-sm text-slate-200">')
lines.append(f'{sp(30)}{{formatDateTime(schedule.nextRunAt)}}')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(26)}</div>')
lines.append(f'{sp(26)}<div>')
lines.append(f'{sp(28)}<div className="text-[11px] uppercase tracking-[0.18em] text-slate-400">')
lines.append(f'{sp(30)}Last Run')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(28)}<div className="mt-1 text-sm text-slate-200">')
lines.append(f'{sp(30)}{{schedule.lastRunAt')
lines.append(f'{sp(32)}? formatDateTime(schedule.lastRunAt)')
lines.append(f'{sp(32)}: "—"}}')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(26)}</div>')
lines.append(f'{sp(26)}<div className="flex xl:justify-end">')
lines.append(f'{sp(28)}<span')
lines.append(f'{sp(30)}className={{`rounded-full border px-2.5 py-1 text-[11px] uppercase tracking-[0.16em] ${{statusClasses(')
lines.append(f'{sp(32)}schedule.status,')
lines.append(f'{sp(30)})}}`}}')
lines.append(f'{sp(28)}}>')
lines.append(f'{sp(30)}{{schedule.status}}')
lines.append(f'{sp(28)}</span>')
lines.append(f'{sp(26)}</div>')
lines.append(f'{sp(24)}</div>')
lines.append(f'{sp(24)}<div className="grid gap-4 xl:grid-cols-[minmax(0,1.4fr)_minmax(0,0.6fr)]">')
lines.append(f'{sp(26)}<div className="min-w-0">')
lines.append(f'{sp(28)}<div className="text-[11px] uppercase tracking-[0.18em] text-slate-400">')
lines.append(f'{sp(30)}Task')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(28)}<div className="mt-1 text-sm leading-6 text-slate-200 break-words">')
lines.append(f'{sp(30)}{{schedule.task}}')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(26)}</div>')
lines.append(f'{sp(26)}<div className="min-w-0">')
lines.append(f'{sp(28)}<div className="text-[11px] uppercase tracking-[0.18em] text-slate-400">')
lines.append(f'{sp(30)}Context')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(28)}<div className="mt-2 flex flex-wrap gap-2">')
lines.append(f'{sp(30)}{{schedule.relatedMission ? (')
lines.append(f'{sp(32)}<Link')
lines.append(f'{sp(34)}href={{`/missions?q=${{encodeURIComponent(schedule.relatedMission)}}`}}')
lines.append(f'{sp(34)}onClick={{(e) => e.stopPropagation()}}')
lines.append(f'{sp(34)}className="rounded-full border border-violet-400/18 bg-violet-500/10 px-2.5 py-1 text-[11px] uppercase tracking-[0.16em] text-violet-200 transition hover:bg-violet-500/15"')
lines.append(f'{sp(32)}}>')
lines.append(f'{sp(34)}Mission · {{schedule.relatedMission}}')
lines.append(f'{sp(32)}</Link>')
lines.append(f'{sp(30)}) : null}}')
lines.append(f'{sp(30)}{{schedule.relatedProductId &&')
lines.append(f'{sp(32)}schedule.relatedProductName ? (')
lines.append(f'{sp(34)}<Link')
lines.append(f'{sp(36)}href={{`/portfolio/${{schedule.relatedProductId}}`}}')
lines.append(f'{sp(36)}onClick={{(e) => e.stopPropagation()}}')
lines.append(f'{sp(36)}className="rounded-full border border-emerald-400/18 bg-emerald-500/10 px-2.5 py-1 text-[11px] uppercase tracking-[0.16em] text-emerald-200 transition hover:bg-emerald-500/15"')
lines.append(f'{sp(34)}}>')
lines.append(f'{sp(36)}Product · {{schedule.relatedProductName}}')
lines.append(f'{sp(34)}</Link>')
lines.append(f'{sp(32)}) : null}}')
lines.append(f'{sp(30)}<Link')
lines.append(f'{sp(32)}href={{`/runs?scheduleId=${{encodeURIComponent(schedule.id)}}`}}')
lines.append(f'{sp(32)}onClick={{(e) => e.stopPropagation()}}')
lines.append(f'{sp(32)}className="rounded-full border border-cyan-300/18 bg-cyan-400/10 px-2.5 py-1 text-[11px] uppercase tracking-[0.16em] text-cyan-200 transition hover:bg-cyan-400/15"')
lines.append(f'{sp(30)}}>')
lines.append(f'{sp(32)}Runs · {{schedule.name}}')
lines.append(f'{sp(30)}</Link>')
lines.append(f'{sp(28)}</div>')
lines.append(f'{sp(26)}</div>')
lines.append(f'{sp(24)}</div>')
lines.append(f'{sp(24)}<div>')
lines.append(f'{sp(26)}<div className="mb-2 flex items-center justify-between text-[11px] uppercase tracking-[0.16em] text-slate-500">')
lines.append(f'{sp(28)}<span>Mission Control Runway</span>')
lines.append(f'{sp(28)}<span className="font-mono">{{schedule.cron}}</span>')
lines.append(f'{sp(26)}</div>')
lines.append(f'{sp(26)}<div className="grid grid-cols-6 gap-2">')
lines.append(f'{sp(28)}{{[0, 1, 2, 3, 4, 5].map((tick) => (')
lines.append(f'{sp(30)}<div')
lines.append(f'{sp(32)}key={{tick}}')
lines.append(f'{sp(32)}className={{`h-2 rounded-full ${{')
lines.append(f'{sp(34)}tick === 1 && schedule.status === "running"')
lines.append(f'{sp(36)}? "bg-cyan-300"')
lines.append(f'{sp(34)}: tick === 2 && schedule.status === "warning"')
lines.append(f'{sp(36)}? "bg-amber-300"')
lines.append(f'{sp(34)}: tick === 3 && schedule.status === "failed"')
lines.append(f'{sp(36)}? "bg-rose-300"')
lines.append(f'{sp(34)}: tick === 4 && schedule.status === "paused"')
lines.append(f'{sp(36)}? "bg-violet-300"')
lines.append(f'{sp(34)}: "bg-white/10"')
lines.append(f'{sp(32)}}}`}}')
lines.append(f'{sp(30)}}')
lines.append(f'{sp(28)}/>)}}')
lines.append(f'{sp(26)}</div>')
lines.append(f'{sp(24)}</div>')
lines.append(f'{sp(22)}</div>')
lines.append(f'{sp(20)}</button>')
lines.append(f'{sp(18)});')
lines.append(f'{sp(16)}}})')
lines.append(f'{sp(14)}];')
lines.append(f'{sp(12)}}})')
lines.append(f'{sp(12)}}})()')
lines.append(f'{sp(10)}}}')
lines.append(f'{sp(10)}{{schedules.length === 0 ? (')
lines.append(f'{sp(12)}<div className="rounded-[18px] border border-dashed border-white/10 bg-white/[0.03] p-6 text-sm text-slate-400">')
lines.append(f'{sp(14)}No schedules match the current filters.')
lines.append(f'{sp(12)}</div>')
lines.append(f'{sp(10)}) : null}}')

sys.stdout.write('\n'.join(lines))